# Generated by Django 3.0.2 on 2020-01-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibson', '0002_auto_20200115_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gibson',
            name='field_name',
            field=models.ImageField(max_length=10000, upload_to='static/img'),
        ),
    ]
